language: node_js
sudo: false
node_js:
    - '0.10'
branches:
    only:
        - master
before_script:
    - npm install -g grunt-cli
after_success:
    # TODO do the opposite before merge ie generate the doc if it's not a PR
    - if [ $TRAVIS_PULL_REQUEST != "false" ] ; then sh bin/generate_apidoc.sh ; fi
env:
    global:
        # TODO: use an ezrobot token
        secure: hzGZ7j6dWYbMwPkPqXHt1L4SIRMW/bO76GVMoZ/+8CH5L3pJie5TIwAssjM/1qhMAABVpSl9Bi79JOqP3nq7fT953yEM7y51OS0RPnc0dbHjyT6q23TlwJj10E4kApPUA5orgQy4eLChS/IrNrAY50bQoz+OEZv8wJHJa3Nr2Tw=
