language: node_js
sudo: false
node_js:
    - '0.10'
branches:
    only:
        - master
before_script:
    - npm install -g grunt-cli
after_success:
    - if [ $TRAVIS_PULL_REQUEST = "false" ] ; then sh bin/generate_apidoc.sh ; fi
env:
    global:
        secure: JO1M7asQCvew+AIXgh++vUDRKMS7S1ZLPJ1HVGPCyG1E1BjTCojwX+IJ0po1FtCWESWjPRr0kVBqLEu5J6g1Pcxx4I2bpgecfRAQS8Bhw2gn5C51OpNcJz7PFjAxg5VwaL4YmIndmInGU+YTU0J3ovLbnnlavpvYklXMXBaYe6M=
